In [4]:
import numpy as np
np.random.seed(10)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))


In [9]:
print(x1)
print(x2)
print(x3)


[9 4 0 1 9 0]
[[1 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]
[[[1 8 4 1 3]
  [6 5 3 9 6]
  [9 1 9 4 2]
  [6 7 8 8 9]]

 [[2 0 6 7 8]
  [1 7 1 4 0]
  [8 5 4 7 8]
  [8 2 6 2 8]]

 [[8 6 6 5 6]
  [0 0 6 9 1]
  [8 9 1 2 8]
  [9 9 5 0 2]]]


In [ ]:
print(x3.ndim) # number of dimensions ndim
print(x3.shape) # shape of the array
print(x3.dtype) # data type of the array
print(x3.size) # number of the elements in the array
print(x3.itemsize) # size of each element in the array
print(x3.nbytes) # total size of the array in bytes, mean size of each element * total number of elements

3
(3, 4, 5)
int64
60
8
480


In [16]:
x1

array([9, 4, 0, 1, 9, 0])

In [19]:
x1[0]

np.int64(9)

In [20]:
x2

array([[1, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [24]:
x2[-1, -1]

np.int64(8)

In [26]:
x2[0, 0] = 12
x2

array([[12,  8,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [27]:
x2[0, 1] = 3.1245
x2

array([[12,  3,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[0:5]

array([0, 1, 2, 3, 4])

In [33]:
x[5:10]

array([5, 6, 7, 8, 9])

In [35]:
x[1::2]

array([1, 3, 5, 7, 9])

In [37]:
x2

array([[12,  3,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [57]:
x2[:3, :3]

array([[12,  3,  9],
       [ 8,  6,  4],
       [ 0,  4,  6]])

In [64]:
x2[2, :4]

array([0, 4, 6, 8])