# axis and reductions

In [2]:
import numpy as np
a = np.array([[1, 2, 3],
                [4, 5, 6]])

In [3]:
a.shape

(2, 3)

In [6]:
a.strides # 24 bytest to got next row # 8 byetes to next element in colun rows = 24, columns = 8)

(24, 8)

In [7]:
np.sum(a)

np.int64(21)

In [8]:
np.mean(a)

np.float64(3.5)

In [9]:
a.mean()

np.float64(3.5)

In [10]:
a.min()

np.int64(1)

In [11]:
a.max()

np.int64(6)

In [12]:
a.std()

np.float64(1.707825127659933)

In [13]:
np.sum(a, axis=0) # this will reduce number or rows # 0th position is rows and 1st axis is to reduce columns

array([5, 7, 9])

In [14]:
np.sum(a, axis=1) # this will reduce number of columns, addition happens column wise

array([ 6, 15])

In [16]:
a.sum(axis=1)

array([ 6, 15])

In [15]:
a.sum(axis=0)

array([5, 7, 9])

In [20]:
b = a.reshape(3, 2)
print(b)
a.shape = (6, 1)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
