In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 4, 5, 6])
a

array([2, 3, 4, 5, 6])

In [3]:
a[0:2]

array([2, 3])

In [4]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
b[0]
b[1, 2]
b[1:3]
b[1][2]
b[1:3, 1:2]

array([[5],
       [8]])

In [6]:
c = b[0:2, 1:3]
c

array([[2, 3],
       [5, 6]])

In [10]:
# print(a.base)
a.base

In [7]:
a.base
b.base
c.base

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
c.base is b

True

In [19]:
d = a[[1,3]]
d
d.base is None

True

In [22]:
e = a[a > 3]
e

array([4, 5, 6])