In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a+10 # adds 10 to each element of the array, 10 is broadcasted to all elements in the array

array([11, 12, 13, 14, 15])

In [3]:
b = np.array([
    [10],
    [20],
    [30]
])
b

array([[10],
       [20],
       [30]])

In [4]:
c = np.array([[10, 20, 30, 40, 50]])

In [5]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(3, 1)
(1, 5)


In [6]:
b+a # a = (5,) converts to (1, 5)
# b = (3, 1))

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [7]:
a+b

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [8]:
d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

e = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

aa = np.array([1, 2, 3])

In [9]:
print(a.shape)
print(aa.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)


(5,)
(3,)
(3, 1)
(1, 5)
(2, 3)
(3, 2)


In [10]:
b + e

array([[20, 30],
       [50, 60],
       [80, 90]])

In [11]:
b + e

array([[20, 30],
       [50, 60],
       [80, 90]])

In [12]:
d + aa

array([[2, 4, 6],
       [5, 7, 9]])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])