In [1]:
import numpy as np
np.random.seed(10)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
x4 = np.random.randint(10, size=(2, 3, 4, 5))


In [2]:
# print(x1)
# print(x2)
# print(x3)
print(x4)


[[[[7 3 0 4 2]
   [0 3 3 1 2]
   [5 9 0 1 0]
   [1 9 0 9 2]]

  [[1 1 0 0 5]
   [9 0 4 6 6]
   [0 2 3 3 2]
   [6 0 5 1 3]]

  [[6 5 5 1 8]
   [0 5 9 8 5]
   [7 8 5 8 9]
   [9 1 5 9 1]]]


 [[[4 7 7 7 9]
   [7 6 0 3 9]
   [4 4 6 8 4]
   [9 2 1 1 6]]

  [[3 4 5 4 0]
   [2 8 0 7 6]
   [5 8 2 2 0]
   [1 2 3 5 7]]

  [[8 7 7 6 9]
   [2 0 4 5 4]
   [6 9 0 4 6]
   [4 9 8 0 7]]]]


In [3]:
print(x3.ndim) # number of dimensions ndim
print(x3.shape) # shape of the array
print(x3.dtype) # data type of the array
print(x3.size) # number of the elements in the array
print(x3.itemsize) # size of each element in the array
print(x3.nbytes) # total size of the array in bytes, mean size of each element * total number of elements

3
(3, 4, 5)
int64
60
8
480


In [4]:
x1

array([9, 4, 0, 1, 9, 0])

In [5]:
x1[0]

np.int64(9)

In [6]:
x2

array([[1, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [7]:
x2[-1, -1]

np.int64(8)

In [8]:
x2[0, 0] = 12
x2

array([[12,  8,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [9]:
x2[0, 1] = 3.1245
x2

array([[12,  3,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[0:5]

array([0, 1, 2, 3, 4])

In [12]:
x[5:10]

array([5, 6, 7, 8, 9])

In [13]:
x[1::2]

array([1, 3, 5, 7, 9])

In [14]:
x2

array([[12,  3,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

In [15]:
x2[:3, :3]

array([[12,  3,  9],
       [ 8,  6,  4],
       [ 0,  4,  6]])

In [16]:
x2[2, :4]

array([0, 4, 6, 8])

In [ ]:
x1 = np.random.randint(10, size=3)
x11 = np.random.randint(10, size=1)



x4= np.random.randint(10, size=4)


x7 = np.random.randint(10, size=(2, 3))
x8 = np.random.randint(10, size=(3, 4))
x9 = np.random.randint(10, size=(4, 3))

In [28]:
print(x1)
print()
print(x4)
print()
print(x7)
print()
print(x8)

[8 3 0]

[9 6 2 3]

[[9 1 4]
 [0 5 0]]

[[8 1 3 6]
 [0 0 6 5]
 [7 4 9 0]]


In [19]:
x1.shape

(3,)

In [20]:
x4.shape

(4,)

In [22]:
x8.shape

(3, 4)

In [25]:
x7.shape

(2, 3)

In [26]:
x1 + x7

array([[17,  4,  4],
       [ 8,  8,  0]])

In [33]:
x4= np.random.randint(10, size=4)
x8 = np.random.randint(10, size=(3, 4))

x4 + x8

array([[11, 18,  3,  1],
       [12, 10,  5,  5],
       [ 9, 13,  3,  5]])

In [31]:
x7 + x9

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [32]:
x1 + x9

array([[ 6, 18,  9],
       [ 8,  9, 11],
       [ 6,  9,  3],
       [ 0, 10, 11]])